# Site settings
name: Ivan Hectors
title: Ivan Hectors | Full Stack Developer
description: Design-minded full-stack developer focused on building beautiful interfaces and experiences
url: https://ivanhectors.github.io/
baseurl: ''
email: ivansnbl@gmail.com
cover: https://ivanhectors.github.io/img/og.png
logo: https://ivanhectors.github.io/img/emojis/technologist.png
resume: https://ivanhectors.github.io/resume.pdf
social:
  - title: email
    url: mailto:ivansnbl@gmail.com
  - title: twitter
    url: https://twitter.com/ivanhectors
  - title: instagram
    url: https://instagram.com/ivanhectors
  - title: facebook
    url: http://facebook.com/ivanhectors
  - title: github
    url: https://github.com/ivanhectors
  - title: linkedin
    url: https://www.linkedin.com/in/ivanhectors
  - title: blog
    url: https://ivanhectors.blogspot.com/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
